#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-hardhat
Version  : 1.2.0
Release  : 9
URL      : https://cran.r-project.org/src/contrib/hardhat_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/hardhat_1.2.0.tar.gz
Summary  : Construct Modeling Packages
Group    : Development/Tools
License  : MIT
Requires: R-glue
Requires: R-rlang
Requires: R-tibble
Requires: R-vctrs
BuildRequires : R-glue
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : R-vctrs
BuildRequires : buildreq-R

%description
generally goes into providing an implementation for a new method that
    is efficient, fast, and correct, but often less emphasis is put on the
    user interface. A good interface requires specialized knowledge about
    S3 methods and formulas, which the average package developer might not
    have.  The goal of 'hardhat' is to reduce the burden around building
    new modeling packages by providing functionality for preprocessing,
    predicting, and validating input.

%prep
%setup -q -n hardhat
cd %{_builddir}/hardhat

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667528553

%install
export SOURCE_DATE_EPOCH=1667528553
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/hardhat/DESCRIPTION
/usr/lib64/R/library/hardhat/INDEX
/usr/lib64/R/library/hardhat/LICENSE
/usr/lib64/R/library/hardhat/Meta/Rd.rds
/usr/lib64/R/library/hardhat/Meta/data.rds
/usr/lib64/R/library/hardhat/Meta/features.rds
/usr/lib64/R/library/hardhat/Meta/hsearch.rds
/usr/lib64/R/library/hardhat/Meta/links.rds
/usr/lib64/R/library/hardhat/Meta/nsInfo.rds
/usr/lib64/R/library/hardhat/Meta/package.rds
/usr/lib64/R/library/hardhat/Meta/vignette.rds
/usr/lib64/R/library/hardhat/NAMESPACE
/usr/lib64/R/library/hardhat/NEWS.md
/usr/lib64/R/library/hardhat/R/hardhat
/usr/lib64/R/library/hardhat/R/hardhat.rdb
/usr/lib64/R/library/hardhat/R/hardhat.rdx
/usr/lib64/R/library/hardhat/data/Rdata.rdb
/usr/lib64/R/library/hardhat/data/Rdata.rds
/usr/lib64/R/library/hardhat/data/Rdata.rdx
/usr/lib64/R/library/hardhat/doc/forge.R
/usr/lib64/R/library/hardhat/doc/forge.Rmd
/usr/lib64/R/library/hardhat/doc/forge.html
/usr/lib64/R/library/hardhat/doc/index.html
/usr/lib64/R/library/hardhat/doc/mold.R
/usr/lib64/R/library/hardhat/doc/mold.Rmd
/usr/lib64/R/library/hardhat/doc/mold.html
/usr/lib64/R/library/hardhat/doc/package.R
/usr/lib64/R/library/hardhat/doc/package.Rmd
/usr/lib64/R/library/hardhat/doc/package.html
/usr/lib64/R/library/hardhat/help/AnIndex
/usr/lib64/R/library/hardhat/help/aliases.rds
/usr/lib64/R/library/hardhat/help/figures/Fitting.png
/usr/lib64/R/library/hardhat/help/figures/Prediction.png
/usr/lib64/R/library/hardhat/help/figures/factor-handling.png
/usr/lib64/R/library/hardhat/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/hardhat/help/figures/logo.png
/usr/lib64/R/library/hardhat/help/hardhat.rdb
/usr/lib64/R/library/hardhat/help/hardhat.rdx
/usr/lib64/R/library/hardhat/help/paths.rds
/usr/lib64/R/library/hardhat/html/00Index.html
/usr/lib64/R/library/hardhat/html/R.css
/usr/lib64/R/library/hardhat/templates/R/constructor.R
/usr/lib64/R/library/hardhat/templates/R/fit.R
/usr/lib64/R/library/hardhat/templates/R/predict.R
/usr/lib64/R/library/hardhat/tests/testthat.R
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/case-weights.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/constructor.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge-recipe.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/mold.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/print.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/shrink.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/table.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/use.md
/usr/lib64/R/library/hardhat/tests/testthat/data-raw/hardhat-0.2.0.R
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-post-mold-recipe-nonstandard-role.rds
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-post-mold-recipe.rds
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-pre-mold-recipe.rds
/usr/lib64/R/library/hardhat/tests/testthat/helper-matrix.R
/usr/lib64/R/library/hardhat/tests/testthat/helper-recipes.R
/usr/lib64/R/library/hardhat/tests/testthat/test-case-weights.R
/usr/lib64/R/library/hardhat/tests/testthat/test-constructor.R
/usr/lib64/R/library/hardhat/tests/testthat/test-delete-response.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-formula.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-recipe.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-xy.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge.R
/usr/lib64/R/library/hardhat/tests/testthat/test-intercept.R
/usr/lib64/R/library/hardhat/tests/testthat/test-levels.R
/usr/lib64/R/library/hardhat/tests/testthat/test-model-matrix.R
/usr/lib64/R/library/hardhat/tests/testthat/test-model-offset.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-formula.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-recipe.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-xy.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold.R
/usr/lib64/R/library/hardhat/tests/testthat/test-print.R
/usr/lib64/R/library/hardhat/tests/testthat/test-scream.R
/usr/lib64/R/library/hardhat/tests/testthat/test-shrink.R
/usr/lib64/R/library/hardhat/tests/testthat/test-spruce.R
/usr/lib64/R/library/hardhat/tests/testthat/test-standardize.R
/usr/lib64/R/library/hardhat/tests/testthat/test-table.R
/usr/lib64/R/library/hardhat/tests/testthat/test-tune.R
/usr/lib64/R/library/hardhat/tests/testthat/test-use.R
/usr/lib64/R/library/hardhat/tests/testthat/test-validation.R
