#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-hardhat
Version  : 1.4.1
Release  : 19
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/hardhat_1.4.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/hardhat_1.4.1.tar.gz
Summary  : Construct Modeling Packages
Group    : Development/Tools
License  : MIT
Requires: R-cli
Requires: R-glue
Requires: R-rlang
Requires: R-sparsevctrs
Requires: R-tibble
Requires: R-vctrs
BuildRequires : R-cli
BuildRequires : R-glue
BuildRequires : R-rlang
BuildRequires : R-sparsevctrs
BuildRequires : R-tibble
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
generally goes into providing an implementation for a new method that
    is efficient, fast, and correct, but often less emphasis is put on the
    user interface. A good interface requires specialized knowledge about
    S3 methods and formulas, which the average package developer might not
    have. The goal of 'hardhat' is to reduce the burden around building
    new modeling packages by providing functionality for preprocessing,
    predicting, and validating input.

%prep
%setup -q -n hardhat
pushd ..
cp -a hardhat buildavx2
popd
pushd ..
cp -a hardhat buildavx512
popd
pushd ..
cp -a hardhat buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740094143

%install
export SOURCE_DATE_EPOCH=1740094143
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/hardhat/DESCRIPTION
/usr/lib64/R/library/hardhat/INDEX
/usr/lib64/R/library/hardhat/LICENSE
/usr/lib64/R/library/hardhat/Meta/Rd.rds
/usr/lib64/R/library/hardhat/Meta/data.rds
/usr/lib64/R/library/hardhat/Meta/features.rds
/usr/lib64/R/library/hardhat/Meta/hsearch.rds
/usr/lib64/R/library/hardhat/Meta/links.rds
/usr/lib64/R/library/hardhat/Meta/nsInfo.rds
/usr/lib64/R/library/hardhat/Meta/package.rds
/usr/lib64/R/library/hardhat/Meta/vignette.rds
/usr/lib64/R/library/hardhat/NAMESPACE
/usr/lib64/R/library/hardhat/NEWS.md
/usr/lib64/R/library/hardhat/R/hardhat
/usr/lib64/R/library/hardhat/R/hardhat.rdb
/usr/lib64/R/library/hardhat/R/hardhat.rdx
/usr/lib64/R/library/hardhat/data/Rdata.rdb
/usr/lib64/R/library/hardhat/data/Rdata.rds
/usr/lib64/R/library/hardhat/data/Rdata.rdx
/usr/lib64/R/library/hardhat/doc/forge.R
/usr/lib64/R/library/hardhat/doc/forge.Rmd
/usr/lib64/R/library/hardhat/doc/forge.html
/usr/lib64/R/library/hardhat/doc/index.html
/usr/lib64/R/library/hardhat/doc/mold.R
/usr/lib64/R/library/hardhat/doc/mold.Rmd
/usr/lib64/R/library/hardhat/doc/mold.html
/usr/lib64/R/library/hardhat/doc/package.R
/usr/lib64/R/library/hardhat/doc/package.Rmd
/usr/lib64/R/library/hardhat/doc/package.html
/usr/lib64/R/library/hardhat/help/AnIndex
/usr/lib64/R/library/hardhat/help/aliases.rds
/usr/lib64/R/library/hardhat/help/figures/Fitting.png
/usr/lib64/R/library/hardhat/help/figures/Prediction.png
/usr/lib64/R/library/hardhat/help/figures/factor-handling.png
/usr/lib64/R/library/hardhat/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/hardhat/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/hardhat/help/figures/logo.png
/usr/lib64/R/library/hardhat/help/hardhat.rdb
/usr/lib64/R/library/hardhat/help/hardhat.rdx
/usr/lib64/R/library/hardhat/help/paths.rds
/usr/lib64/R/library/hardhat/html/00Index.html
/usr/lib64/R/library/hardhat/html/R.css
/usr/lib64/R/library/hardhat/templates/R/constructor.R
/usr/lib64/R/library/hardhat/templates/R/fit.R
/usr/lib64/R/library/hardhat/templates/R/predict.R
/usr/lib64/R/library/hardhat/tests/testthat.R
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/blueprint-formula-default.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/blueprint-recipe.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/blueprint.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/case-weights.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/constructor.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/delete-response.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/encoding.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge-formula.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge-recipe.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge-xy.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/forge.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/intercept.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/levels.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/model-matrix.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/model-offset.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/mold-formula.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/mold-recipe.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/mold-xy.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/mold.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/print.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/quantile-pred.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/recompose.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/scream.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/shrink.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/spruce.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/standardize.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/table.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/tune.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/use.md
/usr/lib64/R/library/hardhat/tests/testthat/_snaps/validation.md
/usr/lib64/R/library/hardhat/tests/testthat/data-raw/hardhat-0.2.0.R
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-post-mold-recipe-nonstandard-role.rds
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-post-mold-recipe.rds
/usr/lib64/R/library/hardhat/tests/testthat/data/hardhat-0.2.0-pre-mold-recipe.rds
/usr/lib64/R/library/hardhat/tests/testthat/helper-matrix.R
/usr/lib64/R/library/hardhat/tests/testthat/helper-sparsevctrs.R
/usr/lib64/R/library/hardhat/tests/testthat/test-blueprint-formula-default.R
/usr/lib64/R/library/hardhat/tests/testthat/test-blueprint-recipe.R
/usr/lib64/R/library/hardhat/tests/testthat/test-blueprint.R
/usr/lib64/R/library/hardhat/tests/testthat/test-case-weights.R
/usr/lib64/R/library/hardhat/tests/testthat/test-constructor.R
/usr/lib64/R/library/hardhat/tests/testthat/test-delete-response.R
/usr/lib64/R/library/hardhat/tests/testthat/test-encoding.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-formula.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-recipe.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge-xy.R
/usr/lib64/R/library/hardhat/tests/testthat/test-forge.R
/usr/lib64/R/library/hardhat/tests/testthat/test-intercept.R
/usr/lib64/R/library/hardhat/tests/testthat/test-levels.R
/usr/lib64/R/library/hardhat/tests/testthat/test-model-matrix.R
/usr/lib64/R/library/hardhat/tests/testthat/test-model-offset.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-formula.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-recipe.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold-xy.R
/usr/lib64/R/library/hardhat/tests/testthat/test-mold.R
/usr/lib64/R/library/hardhat/tests/testthat/test-print.R
/usr/lib64/R/library/hardhat/tests/testthat/test-quantile-pred.R
/usr/lib64/R/library/hardhat/tests/testthat/test-recompose.R
/usr/lib64/R/library/hardhat/tests/testthat/test-scream.R
/usr/lib64/R/library/hardhat/tests/testthat/test-shrink.R
/usr/lib64/R/library/hardhat/tests/testthat/test-spruce.R
/usr/lib64/R/library/hardhat/tests/testthat/test-standardize.R
/usr/lib64/R/library/hardhat/tests/testthat/test-table.R
/usr/lib64/R/library/hardhat/tests/testthat/test-tune.R
/usr/lib64/R/library/hardhat/tests/testthat/test-use.R
/usr/lib64/R/library/hardhat/tests/testthat/test-validation.R
